layers = {   'ch.are.alpenkonvention': ['ch.are.alpenkonvention'],
    'ch.are.gemeindetypen': ['ch.are.gemeindetypen'],
    'ch.astra.ausnahmetransportrouten': ['ch.astra.ausnahmetransportrouten'],
    'ch.astra.ivs-nat': ['ch.astra.ivs-nat'],
    'ch.astra.ivs-nat-verlaeufe': ['ch.astra.ivs-nat-verlaeufe'],
    'ch.astra.ivs-nat_abgrenzungen': ['ch.astra.ivs-nat_abgrenzungen'],
    'ch.astra.ivs-nat_wegbegleiter': ['ch.astra.ivs-nat_wegbegleiter'],
    'ch.astra.ivs-reg_loc': ['ch.astra.ivs-reg_loc'],
    'ch.astra.ivs-reg_loc.sub': ['ch.astra.ivs-reg_loc.sub'],
    'ch.astra.strassenverkehrszaehlung_messstellen-regional_lokal': [   'ch.astra.strassenverkehrszaehlung_messstellen-regional_lokal-status_netz',
                                                                        'ch.astra.strassenverkehrszaehlung_messstellen-regional_lokal-typ'],
    'ch.astra.strassenverkehrszaehlung_messstellen-uebergeordnet': [   'ch.astra.strassenverkehrszaehlung_messstellen-uebergeordnet-status_netz',
                                                                       'ch.astra.strassenverkehrszaehlung_messstellen-uebergeordnet-typ'],
    'ch.babs.kulturgueter': [   'ch.babs.kulturgueter_poly',
                                'ch.babs.kulturgueter_point'],
    'ch.bafu.auen-vegetationskarten': ['ch.bafu.auen-vegetationskarten'],
    'ch.bafu.bundesinventare-amphibien': ['ch.bafu.bundesinventare-amphibien'],
    'ch.bafu.bundesinventare-amphibien_anhoerung': [   'ch.bafu.bundesinventare-amphibien_anhoerung'],
    'ch.bafu.bundesinventare-amphibien_wanderobjekte': [   'ch.bafu.bundesinventare-amphibien_wanderobjekte'],
    'ch.bafu.bundesinventare-amphibien_wanderobjekte_anhoerung': [   'ch.bafu.bundesinventare-amphibien_wanderobjekte_anhoerung'],
    'ch.bafu.bundesinventare-auen': ['ch.bafu.bundesinventare-auen'],
    'ch.bafu.bundesinventare-auen_anhoerung': [   'ch.bafu.bundesinventare-auen_anhoerung'],
    'ch.bafu.bundesinventare-bln': ['ch.bafu.bundesinventare-bln'],
    'ch.bafu.bundesinventare-flachmoore': [   'ch.bafu.bundesinventare-flachmoore'],
    'ch.bafu.bundesinventare-flachmoore_anhoerung': [   'ch.bafu.bundesinventare-flachmoore_anhoerung'],
    'ch.bafu.bundesinventare-hochmoore': ['ch.bafu.bundesinventare-hochmoore'],
    'ch.bafu.bundesinventare-hochmoore_anhoerung': [   'ch.bafu.bundesinventare-hochmoore_anhoerung'],
    'ch.bafu.bundesinventare-jagdbanngebiete': [   'ch.bafu.bundesinventare-jagdbanngebiete'],
    'ch.bafu.bundesinventare-moorlandschaften': [   'ch.bafu.bundesinventare-moorlandschaften'],
    'ch.bafu.bundesinventare-trockenwiesen_trockenweiden': [   'ch.bafu.bundesinventare-trockenwiesen_trockenweiden'],
    'ch.bafu.bundesinventare-trockenwiesen_trockenweiden_anhoerung': [   'ch.bafu.bundesinventare-trockenwiesen_trockenweiden_anhoerung'],
    'ch.bafu.bundesinventare-vogelreservate': [   'ch.bafu.bundesinventare-vogelreservate'],
    'ch.bafu.fauna-steinbockkolonien': ['ch.bafu.fauna-steinbockkolonien'],
    'ch.bafu.flussordnungszahlen-strahler': [   'ch.bafu.flussordnungszahlen-strahler'],
    'ch.bafu.gewaesserschutzbereiche': ['ch.bafu.gewaesserschutzbereiche'],
    'ch.bafu.grundwasserschutzareale': ['ch.bafu.grundwasserschutzareale'],
    'ch.bafu.grundwasserschutzzonen': ['ch.bafu.grundwasserschutzzonen'],
    'ch.bafu.hydrologie-gewaesserzustandsmessstationen': [   'ch.bafu.hydrologie-gewaesserzustandsmessstationen'],
    'ch.bafu.hydrologie-hintergrundkarte': [   'ch.bafu.hydrologie-hintergrundkarte_grenzen',
                                               'ch.bafu.hydrologie-hintergrundkarte_grenzen',
                                               'ch.bafu.hydrologie-hintergrundkarte_gewaesser',
                                               'ch.bafu.hydrologie-hintergrundkarte_staedte'],
    'ch.bafu.hydrologie-hydromessstationen': [   'ch.bafu.hydrologie-hydromessstationen'],
    'ch.bafu.hydrologie-messstationen_gefahren': [   'ch.bafu.hydrologie-messstationen_gefahren'],
    'ch.bafu.hydrologie-wassertemperaturmessstationen': [   'ch.bafu.hydrologie-wassertemperaturmessstationen'],
    'ch.bafu.hydroweb-messstationen_gefahren': [   'ch.bafu.hydroweb-messstationen_gefahren'],
    'ch.bafu.hydroweb-messstationen_grundwasser': [   'ch.bafu.hydroweb-messstationen_grundwasser'],
    'ch.bafu.hydroweb-messstationen_temperatur': [   'ch.bafu.hydroweb-messstationen_temperatur'],
    'ch.bafu.hydroweb-messstationen_vorhersage': [   'ch.bafu.hydroweb-messstationen_vorhersage'],
    'ch.bafu.hydroweb-messstationen_zustand': [   'ch.bafu.hydroweb-messstationen_zustand'],
    'ch.bafu.hydroweb-warnkarte_national': [   'ch.bafu.hydroweb-warnkarte_national_polygon',
                                               'ch.bafu.hydroweb-warnkarte_national_line'],
    'ch.bafu.hydroweb-warnkarte_regional': [   'ch.bafu.hydroweb-warnkarte_regional'],
    'ch.bafu.moose': ['ch.bafu.moose'],
    'ch.bafu.nabelstationen': ['ch.bafu.nabelstationen'],
    'ch.bafu.oekomorphologie-f_abschnitte': [   'ch.bafu.oekomorphologie-f_abschnitte'],
    'ch.bafu.oekomorphologie-f_abstuerze': [   'ch.bafu.oekomorphologie-f_abstuerze'],
    'ch.bafu.oekomorphologie-f_bauwerke': [   'ch.bafu.oekomorphologie-f_bauwerke'],
    'ch.bafu.ren-extensive_landwirtschaftsgebiete': [   'ch.bafu.ren-extensive_landwirtschaftsgebiete'],
    'ch.bafu.ren-feuchtgebiete': ['ch.bafu.ren-feuchtgebiete'],
    'ch.bafu.ren-fliessgewaesser_seen': ['ch.bafu.ren-fliessgewaesser_seen'],
    'ch.bafu.ren-trockenstandorte': ['ch.bafu.ren-trockenstandorte'],
    'ch.bafu.ren-wald': ['ch.bafu.ren-wald'],
    'ch.bafu.schutzgebiete-paerke_nationaler_bedeutung': [   'ch.bafu.schutzgebiete-paerke_nationaler_bedeutung'],
    'ch.bafu.schutzgebiete-ramsar': ['ch.bafu.schutzgebiete-ramsar'],
    'ch.bafu.schutzgebiete-schweizerischer_nationalpark': [   'ch.bafu.schutzgebiete-schweizerischer_nationalpark'],
    'ch.bafu.schutzgebiete-smaragd': ['ch.bafu.schutzgebiete-smaragd'],
    'ch.bafu.showme-gemeinden_hochwasser': [   'ch.bafu.showme-gemeinden_hochwasser'],
    'ch.bafu.showme-gemeinden_lawinen': ['ch.bafu.showme-gemeinden_lawinen'],
    'ch.bafu.showme-gemeinden_rutschungen': [   'ch.bafu.showme-gemeinden_rutschungen'],
    'ch.bafu.showme-gemeinden_sturzprozesse': [   'ch.bafu.showme-gemeinden_sturzprozesse'],
    'ch.bafu.showme-kantone_hochwasser': ['ch.bafu.showme-kantone_hochwasser'],
    'ch.bafu.showme-kantone_lawinen': ['ch.bafu.showme-kantone_lawinen'],
    'ch.bafu.showme-kantone_rutschungen': [   'ch.bafu.showme-kantone_rutschungen'],
    'ch.bafu.showme-kantone_sturzprozesse': [   'ch.bafu.showme-kantone_sturzprozesse'],
    'ch.bafu.sturm-boeenspitzen_100': ['ch.bafu.sturm-boeenspitzen_100'],
    'ch.bafu.sturm-boeenspitzen_30': ['ch.bafu.sturm-boeenspitzen_30'],
    'ch.bafu.sturm-boeenspitzen_300': ['ch.bafu.sturm-boeenspitzen_300'],
    'ch.bafu.sturm-boeenspitzen_50': ['ch.bafu.sturm-boeenspitzen_50'],
    'ch.bafu.sturm-staudruck_100': ['ch.bafu.sturm-staudruck_100'],
    'ch.bafu.sturm-staudruck_30': ['ch.bafu.sturm-staudruck_30'],
    'ch.bafu.sturm-staudruck_300': ['ch.bafu.sturm-staudruck_300'],
    'ch.bafu.sturm-staudruck_50': ['ch.bafu.sturm-staudruck_50'],
    'ch.bafu.unesco-weltnaturerbe': ['ch.bafu.unesco-weltnaturerbe'],
    'ch.bafu.wasser-entnahme': [   'ch.bafu.wasser-entnahme-wasserkraft-weitere',
                                   'ch.bafu.wasser-entnahme-wasserkraft-bedeutend',
                                   'ch.bafu.wasser-entnahme-andere_nutzung-weitere',
                                   'ch.bafu.wasser-entnahme-andere_nutzung-bedeutend'],
    'ch.bafu.wasser-gebietsauslaesse': ['ch.bafu.wasser-gebietsauslaesse'],
    'ch.bafu.wasser-leitungen': ['ch.bafu.wasser-leitungen'],
    'ch.bafu.wasser-rueckgabe': ['ch.bafu.wasser-rueckgabe'],
    'ch.bafu.wasser-teileinzugsgebiete_2': [   'ch.bafu.wasser-teileinzugsgebiete_2'],
    'ch.bafu.wasser-teileinzugsgebiete_40': [   'ch.bafu.wasser-teileinzugsgebiete_40'],
    'ch.bafu.wasser-vorfluter': ['ch.bafu.wasser-vorfluter'],
    'ch.bafu.wrz-jagdbanngebiete_select': [   'ch.bafu.wrz-jagdbanngebiete_select_polygon',
                                              'ch.bafu.wrz-wildruhezonen-jagdbanngebiete-wege-routen_select'],
    'ch.bafu.wrz-wildruhezonen_portal': [   'ch.bafu.wrz-wildruhezonen_portal_polygon',
                                            'ch.bafu.wrz-wildruhezonen-jagdbanngebiete-wege-routen_dummy'],
    'ch.bag.zecken-lyme': ['ch.bag.zecken-lyme'],
    'ch.bak.bundesinventar-schuetzenswerte-ortsbilder': [   'ch.bak.bundesinventar-schuetzenswerte-ortsbilder'],
    'ch.bak.schutzgebiete-unesco_weltkulturerbe': [   'ch.bak.schutzgebiete-unesco_weltkulturerbe_polygone',
                                                      'ch.bak.schutzgebiete-unesco_weltkulturerbe_overview_polygone',
                                                      'ch.bak.schutzgebiete-unesco_weltkulturerbe_overview_point'],
    'ch.bakom.anbieter-eigenes_festnetz': [   'ch.bakom.anbieter-eigenes_festnetz'],
    'ch.bakom.anschlussart-glasfaser': ['ch.bakom.anschlussart-glasfaser'],
    'ch.bakom.anschlussart-koaxialkabel': [   'ch.bakom.anschlussart-koaxialkabel'],
    'ch.bakom.anschlussart-kupferdraht': ['ch.bakom.anschlussart-kupferdraht'],
    'ch.bakom.downlink1': ['ch.bakom.downlink1'],
    'ch.bakom.downlink10': ['ch.bakom.downlink10'],
    'ch.bakom.downlink100': ['ch.bakom.downlink100'],
    'ch.bakom.downlink2': ['ch.bakom.downlink2'],
    'ch.bakom.downlink20': ['ch.bakom.downlink20'],
    'ch.bakom.downlink50': ['ch.bakom.downlink50'],
    'ch.bakom.mobil-antennenstandorte-gsm': [   'ch.bakom.mobil-antennenstandorte-gsm'],
    'ch.bakom.mobil-antennenstandorte-lte': [   'ch.bakom.mobil-antennenstandorte-lte'],
    'ch.bakom.mobil-antennenstandorte-umts': [   'ch.bakom.mobil-antennenstandorte-umts'],
    'ch.bakom.radio-fernsehsender': ['ch.bakom.radio-fernsehsender'],
    'ch.bakom.uplink1': ['ch.bakom.uplink1'],
    'ch.bakom.uplink10': ['ch.bakom.uplink10'],
    'ch.bakom.uplink100': ['ch.bakom.uplink100'],
    'ch.bakom.uplink2': ['ch.bakom.uplink2'],
    'ch.bakom.uplink20': ['ch.bakom.uplink20'],
    'ch.bakom.uplink50': ['ch.bakom.uplink50'],
    'ch.bakom.verfuegbarkeit-hdtv': ['ch.bakom.verfuegbarkeit-hdtv'],
    'ch.bakom.verfuegbarkeit-tv': ['ch.bakom.verfuegbarkeit-tv'],
    'ch.bakom.versorgungsgebiet-tv': ['ch.bakom.versorgungsgebiet-tv'],
    'ch.bakom.versorgungsgebiet-ukw': ['ch.bakom.versorgungsgebiet-ukw'],
    'ch.bav.haltestellen-oev': ['ch.bav.haltestellen-oev'],
    'ch.bav.kataster-belasteter-standorte-oev': [   'ch.bav.kataster-belasteter-standorte-oev_polygon',
                                                    'ch.bav.kataster-belasteter-standorte-oev_lines'],
    'ch.bav.kataster-belasteter-standorte-oev.oereb': [   'ch.bav.kataster-belasteter-standorte-oev.oereb_polygon',
                                                          'ch.bav.kataster-belasteter-standorte-oev.oereb_line'],
    'ch.bav.laerm-emissionsplan_eisenbahn_nacht': [   'ch.bav.laerm-emissionsplan_eisenbahn_nacht'],
    'ch.bav.laerm-emissionsplan_eisenbahn_tag': [   'ch.bav.laerm-emissionsplan_eisenbahn_tag'],
    'ch.bav.sachplan-infrastruktur-schiene_anhorung': [   'ch.bav.sachplan-infrastruktur-schiene_anhorung_m01a',
                                                          'ch.bav.sachplan-infrastruktur-schiene_anhorung_m01b',
                                                          'ch.bav.sachplan-infrastruktur-schiene_anhorung_m01c',
                                                          'ch.bav.sachplan-infrastruktur-schiene_anhorung_polygons_pl',
                                                          'ch.bav.sachplan-infrastruktur-schiene_anhorung_polygons_pl_r',
                                                          'ch.bav.sachplan-infrastruktur-schiene_anhorung_lines_fac_minscale',
                                                          'ch.bav.sachplan-infrastruktur-schiene_anhorung_lines_fac_maxscale',
                                                          'ch.bav.sachplan-infrastruktur-schiene_anhorung_points_fac',
                                                          'ch.bav.sachplan-infrastruktur-schiene_anhorung_points_fac'],
    'ch.bav.sachplan-infrastruktur-schiene_ausgangslage': [   'ch.bav.sachplan-infrastruktur-schiene_ausgangslage_lines_minscale',
                                                              'ch.bav.sachplan-infrastruktur-schiene_ausgangslage_lines_maxscale',
                                                              'ch.bav.sachplan-infrastruktur-schiene_ausgangslage_points_minscale',
                                                              'ch.bav.sachplan-infrastruktur-schiene_ausgangslage_points_maxscale'],
    'ch.bav.sachplan-infrastruktur-schiene_kraft': [   'ch.bav.sachplan-infrastruktur-schiene_kraft_m01a',
                                                       'ch.bav.sachplan-infrastruktur-schiene_kraft_m01b',
                                                       'ch.bav.sachplan-infrastruktur-schiene_kraft_m01c',
                                                       'ch.bav.sachplan-infrastruktur-schiene_kraft_polygons_pl',
                                                       'ch.bav.sachplan-infrastruktur-schiene_kraft_polygons_pl_r',
                                                       'ch.bav.sachplan-infrastruktur-schiene_kraft_lines_fac_minscale',
                                                       'ch.bav.sachplan-infrastruktur-schiene_kraft_lines_fac_maxscale',
                                                       'ch.bav.sachplan-infrastruktur-schiene_kraft_points_fac',
                                                       'ch.bav.sachplan-infrastruktur-schiene_kraft_points_fac'],
    'ch.bav.sachplan-infrastruktur-schifffahrt_anhoerung': [   'ch.bav.sachplan-infrastruktur-schifffahrt_anhoerung_polygons',
                                                               'ch.bav.sachplan-infrastruktur-schifffahrt_anhoerung_polygons_raster',
                                                               'ch.bav.sachplan-infrastruktur-schifffahrt_anhoerung_linie1',
                                                               'ch.bav.sachplan-infrastruktur-schifffahrt_anhoerung_linie2',
                                                               'ch.bav.sachplan-infrastruktur-schifffahrt_anhoerung_linie3',
                                                               'ch.bav.sachplan-infrastruktur-schifffahrt_anhoerung_linie4'],
    'ch.bav.sachplan-infrastruktur-schifffahrt_ausgangslage': [   'ch.bav.sachplan-infrastruktur-schifffahrt_ausgangslage'],
    'ch.bazl.kataster-belasteter-standorte-zivilflugplaetze': [   'ch.bazl.kataster-belasteter-standorte-zivilflugplaetze_polygon',
                                                                  'ch.bazl.kataster-belasteter-standorte-zivilflugplaetze_lines',
                                                                  'ch.bazl.kataster-belasteter-standorte-zivilflugplaetze_points'],
    'ch.bazl.kataster-belasteter-standorte-zivilflugplaetze.oereb': [   'ch.bazl.kataster-belasteter-standorte-zivilflugplaetze.oereb_polygon',
                                                                        'ch.bazl.kataster-belasteter-standorte-zivilflugplaetze.oereb_line',
                                                                        'ch.bazl.kataster-belasteter-standorte-zivilflugplaetze.oereb_points'],
    'ch.bazl.laermbelastungskataster-zivilflugplaetze_erste-nachtstunde': [   'ch.bazl.laermbelastungskataster-zivilflugplaetze_erste-nachtstunde'],
    'ch.bazl.laermbelastungskataster-zivilflugplaetze_helikopter': [   'ch.bazl.laermbelastungskataster-zivilflugplaetze_helikopter'],
    'ch.bazl.laermbelastungskataster-zivilflugplaetze_helikopter-maximalpegel': [   'ch.bazl.laermbelastungskataster-zivilflugplaetze_helikopter-maximalpegel'],
    'ch.bazl.laermbelastungskataster-zivilflugplaetze_klein-grossflugzeuge': [   'ch.bazl.laermbelastungskataster-zivilflugplaetze_klein-grossflugzeuge'],
    'ch.bazl.laermbelastungskataster-zivilflugplaetze_kleinluftfahrzeuge': [   'ch.bazl.laermbelastungskataster-zivilflugplaetze_kleinluftfahrzeuge'],
    'ch.bazl.laermbelastungskataster-zivilflugplaetze_letzte-nachtstunde': [   'ch.bazl.laermbelastungskataster-zivilflugplaetze_letzte-nachtstunde'],
    'ch.bazl.laermbelastungskataster-zivilflugplaetze_militaer-gesamt': [   'ch.bazl.laermbelastungskataster-zivilflugplaetze_militaer-gesamt'],
    'ch.bazl.laermbelastungskataster-zivilflugplaetze_zweite-nachtstunde': [   'ch.bazl.laermbelastungskataster-zivilflugplaetze_zweite-nachtstunde'],
    'ch.bazl.luftfahrthindernis': [   'ch.bazl.luftfahrthindernis_poly',
                                      'ch.bazl.luftfahrthindernis_line',
                                      'ch.bazl.luftfahrthindernis_point'],
    'ch.bazl.projektierungszonen-flughafenanlagen': [   'ch.bazl.projektierungszonen-flughafenanlagen'],
    'ch.bazl.projektierungszonen-flughafenanlagen.oereb': [   'ch.bazl.projektierungszonen-flughafenanlagen.oereb'],
    'ch.bazl.sachplan-infrastruktur-luftfahrt_anhorung': [   'ch.bazl.sachplan-infrastruktur-luftfahrt_anhorung_points_aufhebung',
                                                             'ch.bazl.sachplan-infrastruktur-luftfahrt_anhorung_points_plan',
                                                             'ch.bazl.sachplan-infrastruktur-luftfahrt_anhorung_points',
                                                             'ch.bazl.sachplan-infrastruktur-luftfahrt_anhorung_surfaces_fac',
                                                             'ch.bazl.sachplan-infrastruktur-luftfahrt_anhorung_surfaces',
                                                             'ch.bazl.sachplan-infrastruktur-luftfahrt_anhorung_surfaces_raster',
                                                             'ch.bazl.sachplan-infrastruktur-luftfahrt_anhorung_surfaces_raster'],
    'ch.bazl.sachplan-infrastruktur-luftfahrt_kraft': [   'ch.bazl.sachplan-infrastruktur-luftfahrt_kraft_points_aufhebung',
                                                          'ch.bazl.sachplan-infrastruktur-luftfahrt_kraft_points_plan',
                                                          'ch.bazl.sachplan-infrastruktur-luftfahrt_kraft_points',
                                                          'ch.bazl.sachplan-infrastruktur-luftfahrt_kraft_surfaces_fac',
                                                          'ch.bazl.sachplan-infrastruktur-luftfahrt_kraft_surfaces',
                                                          'ch.bazl.sachplan-infrastruktur-luftfahrt_kraft_surfaces_raster',
                                                          'ch.bazl.sachplan-infrastruktur-luftfahrt_kraft_surfaces_raster'],
    'ch.bazl.sicherheitszonenplan': ['ch.bazl.sicherheitszonenplan'],
    'ch.bazl.sicherheitszonenplan.oereb': [   'ch.bazl.sicherheitszonenplan.oereb'],
    'ch.bfe.abgeltung-wasserkraftnutzung': [   'ch.bfe.abgeltung-wasserkraftnutzung'],
    'ch.bfe.energieforschung': ['ch.bfe.energieforschung'],
    'ch.bfe.energiestaedte': ['ch.bfe.energiestaedte'],
    'ch.bfe.energiestaedte-2000watt-areale': [   'ch.bfe.energiestaedte-2000watt-areale'],
    'ch.bfe.energiestaedte-2000watt-aufdemweg': [   'ch.bfe.energiestaedte-2000watt-aufdemweg'],
    'ch.bfe.energiestaedte-energieregionen': [   'ch.bfe.energiestaedte-energieregionen'],
    'ch.bfe.kernkraftwerke': ['ch.bfe.kernkraftwerke'],
    'ch.bfe.kleinwasserkraftpotentiale': ['ch.bfe.kleinwasserkraftpotentiale'],
    'ch.bfe.sachplan-geologie-tiefenlager': [   'ch.bfe.sachplan-geologie-tiefenlager_planning_raster',
                                                'ch.bfe.sachplan-geologie-tiefenlager_planning_raster_ov',
                                                'ch.bfe.sachplan-geologie-tiefenlager_planning',
                                                'ch.bfe.sachplan-geologie-tiefenlager_planning_ov',
                                                'ch.bfe.sachplan-geologie-tiefenlager_facilities'],
    'ch.bfe.sachplan-geologie-tiefenlager-thematische-darstellung': [   'ch.bfe.sachplan-geologie-tiefenlager-thematische-darstellung_planning',
                                                                        'ch.bfe.sachplan-geologie-tiefenlager-thematische-darstellung_planning_ov',
                                                                        'ch.bfe.sachplan-geologie-tiefenlager-thematische-darstellung_planning_raster',
                                                                        'ch.bfe.sachplan-geologie-tiefenlager-thematische-darstellung_planning_raster_ov',
                                                                        'ch.bfe.sachplan-geologie-tiefenlager-thematische-darstellung_facilities'],
    'ch.bfe.sachplan-uebertragungsleitungen_anhoerung': [   'ch.bfe.sachplan-uebertragungsleitungen_anhoerung_fac_points',
                                                            'ch.bfe.sachplan-uebertragungsleitungen_anhoerung_fac_r_points',
                                                            'ch.bfe.sachplan-uebertragungsleitungen_anhoerung_pl_points',
                                                            'ch.bfe.sachplan-uebertragungsleitungen_anhoerung_pl_r_points',
                                                            'ch.bfe.sachplan-uebertragungsleitungen_anhoerung_pl_poly',
                                                            'ch.bfe.sachplan-uebertragungsleitungen_anhoerung_pl_r_poly'],
    'ch.bfe.sachplan-uebertragungsleitungen_kraft': [   'ch.bfe.sachplan-uebertragungsleitungen_kraft_fac_points',
                                                        'ch.bfe.sachplan-uebertragungsleitungen_kraft_fac_r_points',
                                                        'ch.bfe.sachplan-uebertragungsleitungen_kraft_pl_points',
                                                        'ch.bfe.sachplan-uebertragungsleitungen_kraft_pl_r_points',
                                                        'ch.bfe.sachplan-uebertragungsleitungen_kraft_pl_poly',
                                                        'ch.bfe.sachplan-uebertragungsleitungen_kraft_pl_r_poly'],
    'ch.bfe.solarenergie-eignung-daecher': [   'ch.bfe.solarenergie-eignung-daecher'],
    'ch.bfe.statistik-wasserkraftanlagen': [   'ch.bfe.statistik-wasserkraftanlagen'],
    'ch.bfe.stauanlagen-bundesaufsicht': ['ch.bfe.stauanlagen-bundesaufsicht'],
    'ch.bfe.windenergieanlagen': ['ch.bfe.windenergieanlagen'],
    'ch.bfs.arealstatistik': [   'ch.bfs.arealstatistik-cross',
                                 'ch.bfs.arealstatistik-punkte'],
    'ch.bfs.arealstatistik-1985': [   'ch.bfs.arealstatistik-1985-cross',
                                      'ch.bfs.arealstatistik-1985-punkte'],
    'ch.bfs.arealstatistik-1997': [   'ch.bfs.arealstatistik-1997-cross',
                                      'ch.bfs.arealstatistik-1997-punkte'],
    'ch.bfs.arealstatistik-bodenbedeckung': [   'ch.bfs.arealstatistik-bodenbedeckung-cross',
                                                'ch.bfs.arealstatistik-bodenbedeckung-punkte'],
    'ch.bfs.arealstatistik-bodenbedeckung-1985': [   'ch.bfs.arealstatistik-bodenbedeckung-1985-cross',
                                                     'ch.bfs.arealstatistik-bodenbedeckung-1985-punkte'],
    'ch.bfs.arealstatistik-bodenbedeckung-1997': [   'ch.bfs.arealstatistik-bodenbedeckung-1997-cross',
                                                     'ch.bfs.arealstatistik-bodenbedeckung-1997-punkte'],
    'ch.bfs.arealstatistik-bodennutzung': [   'ch.bfs.arealstatistik-bodennutzung-cross',
                                              'ch.bfs.arealstatistik-bodennutzung-punkte'],
    'ch.bfs.arealstatistik-bodennutzung-1985': [   'ch.bfs.arealstatistik-bodennutzung-1985-cross',
                                                   'ch.bfs.arealstatistik-bodennutzung-1985-punkte'],
    'ch.bfs.arealstatistik-bodennutzung-1997': [   'ch.bfs.arealstatistik-bodennutzung-1997-cross',
                                                   'ch.bfs.arealstatistik-bodennutzung-1997-punkte'],
    'ch.bfs.gebaeude_wohnungs_register': [   'ch.bfs.gebaeude_wohnungs_register-label',
                                             'ch.bfs.gebaeude_wohnungs_register-without_label'],
    'ch.blw.alpprodukte': ['ch.blw.alpprodukte'],
    'ch.blw.bergprodukte': ['ch.blw.bergprodukte'],
    'ch.blw.bodeneignung-gruendigkeit': ['ch.blw.bodeneignung-gruendigkeit'],
    'ch.blw.bodeneignung-kulturland': ['ch.blw.bodeneignung-kulturland'],
    'ch.blw.bodeneignung-kulturtyp': ['ch.blw.bodeneignung-kulturtyp'],
    'ch.blw.bodeneignung-naehrstoffspeichervermoegen': [   'ch.blw.bodeneignung-naehrstoffspeichervermoegen'],
    'ch.blw.bodeneignung-skelettgehalt': ['ch.blw.bodeneignung-skelettgehalt'],
    'ch.blw.bodeneignung-vernaessung': ['ch.blw.bodeneignung-vernaessung'],
    'ch.blw.bodeneignung-wasserdurchlaessigkeit': [   'ch.blw.bodeneignung-wasserdurchlaessigkeit'],
    'ch.blw.bodeneignung-wasserspeichervermoegen': [   'ch.blw.bodeneignung-wasserspeichervermoegen'],
    'ch.blw.emapis-beizugsgebiet': ['ch.blw.emapis-beizugsgebiet'],
    'ch.blw.emapis-bewaesserung': [   'ch.blw.emapis-bewaesserung_poly',
                                      'ch.blw.emapis-bewaesserung_lines',
                                      'ch.blw.emapis-bewaesserung_points'],
    'ch.blw.emapis-elektrizitaetsversorgung': [   'ch.blw.emapis-elektrizitaetsversorgung_lines',
                                                  'ch.blw.emapis-elektrizitaetsversorgung_points'],
    'ch.blw.emapis-entwaesserung': [   'ch.blw.emapis-entwaesserung_poly',
                                       'ch.blw.emapis-entwaesserung_lines',
                                       'ch.blw.emapis-entwaesserung_point'],
    'ch.blw.emapis-hochbau': ['ch.blw.emapis-hochbau'],
    'ch.blw.emapis-milchleitung': [   'ch.blw.emapis-milchleitung_lines',
                                      'ch.blw.emapis-milchleitung_points'],
    'ch.blw.emapis-oekologie': [   'ch.blw.emapis-oekologie_poly',
                                   'ch.blw.emapis-oekologie_lines'],
    'ch.blw.emapis-projektschwerpunkt': ['ch.blw.emapis-projektschwerpunkt'],
    'ch.blw.emapis-seilbahnen': [   'ch.blw.emapis-seilbahnen_lines',
                                    'ch.blw.emapis-seilbahnen_points'],
    'ch.blw.emapis-wasserversorgung': [   'ch.blw.emapis-wasserversorgung_lines',
                                          'ch.blw.emapis-wasserversorgung_points'],
    'ch.blw.emapis-wegebau': [   'ch.blw.emapis-wegebau_lines',
                                 'ch.blw.emapis-wegebau_points'],
    'ch.blw.emapis-zusammenfassung': [   'ch.blw.emapis-zusammenfassung_points',
                                         'ch.blw.emapis-zusammenfassung_lines',
                                         'ch.blw.emapis-zusammenfassung_polygon'],
    'ch.blw.feldblockkarte': ['ch.blw.feldblockkarte'],
    'ch.blw.hang_steillagen': ['ch.blw.hang_steillagen'],
    'ch.blw.klimaeignung-futterbau': ['ch.blw.klimaeignung-futterbau'],
    'ch.blw.klimaeignung-getreidebau': ['ch.blw.klimaeignung-getreidebau'],
    'ch.blw.klimaeignung-kartoffeln': ['ch.blw.klimaeignung-kartoffeln'],
    'ch.blw.klimaeignung-koernermais': ['ch.blw.klimaeignung-koernermais'],
    'ch.blw.klimaeignung-kulturland': ['ch.blw.klimaeignung-kulturland'],
    'ch.blw.klimaeignung-spezialkulturen': [   'ch.blw.klimaeignung-spezialkulturen'],
    'ch.blw.klimaeignung-typ': ['ch.blw.klimaeignung-typ'],
    'ch.blw.klimaeignung-zwischenfruchtbau': [   'ch.blw.klimaeignung-zwischenfruchtbau'],
    'ch.blw.landwirtschaftliche-zonengrenzen': [   'ch.blw.landwirtschaftliche-zonengrenzen'],
    'ch.blw.niederschlagshaushalt': ['ch.blw.niederschlagshaushalt'],
    'ch.blw.steil_terrassenlagen_rebbau': [   'ch.blw.steil_terrassenlagen_rebbau'],
    'ch.blw.ursprungsbezeichnungen-fleisch': [   'ch.blw.ursprungsbezeichnungen-fleisch-buendnerfleisch',
                                                 'ch.blw.ursprungsbezeichnungen-fleisch-gl_kaelberwurst',
                                                 'ch.blw.ursprungsbezeichnungen-fleisch-longeole',
                                                 'ch.blw.ursprungsbezeichnungen-fleisch-saucisse_ajoie',
                                                 'ch.blw.ursprungsbezeichnungen-fleisch-saucisse_aux_choux_vd',
                                                 'ch.blw.ursprungsbezeichnungen-fleisch-saucisse_ne',
                                                 'ch.blw.ursprungsbezeichnungen-fleisch-saucisson_vd',
                                                 'ch.blw.ursprungsbezeichnungen-fleisch-sg_wuerste',
                                                 'ch.blw.ursprungsbezeichnungen-fleisch-vs_trockenfleisch'],
    'ch.blw.ursprungsbezeichnungen-kaese': [   'ch.blw.ursprungsbezeichnungen-kaese-be_alpkaese',
                                               'ch.blw.ursprungsbezeichnungen-kaese-emmentaler',
                                               'ch.blw.ursprungsbezeichnungen-kaese-etivaz',
                                               'ch.blw.ursprungsbezeichnungen-kaese-formaggio_d_alpe_ti',
                                               'ch.blw.ursprungsbezeichnungen-kaese-glarner_alpkaese',
                                               'ch.blw.ursprungsbezeichnungen-kaese-gruyere',
                                               'ch.blw.ursprungsbezeichnungen-kaese-sbrinz',
                                               'ch.blw.ursprungsbezeichnungen-kaese-tete_de_moine',
                                               'ch.blw.ursprungsbezeichnungen-kaese-vacherin_fr',
                                               'ch.blw.ursprungsbezeichnungen-kaese-vacherin_mont_d_or',
                                               'ch.blw.ursprungsbezeichnungen-kaese-vs_raclette',
                                               'ch.blw.ursprungsbezeichnungen-kaese-werdenberger'],
    'ch.blw.ursprungsbezeichnungen-konditoreiwaren': [   'ch.blw.ursprungsbezeichnungen-konditoreiwaren'],
    'ch.blw.ursprungsbezeichnungen-pflanzen': [   'ch.blw.ursprungsbezeichnungen-pflanzen-cardon_epineux_ge',
                                                  'ch.blw.ursprungsbezeichnungen-pflanzen-munder_safran',
                                                  'ch.blw.ursprungsbezeichnungen-pflanzen-poire_botzi',
                                                  'ch.blw.ursprungsbezeichnungen-pflanzen-rheintaler_ribel',
                                                  'ch.blw.ursprungsbezeichnungen-pflanzen-vs_roggenbrot'],
    'ch.blw.ursprungsbezeichnungen-spirituosen': [   'ch.blw.ursprungsbezeichnungen-spirituosen-abricotine',
                                                     'ch.blw.ursprungsbezeichnungen-spirituosen-damassine',
                                                     'ch.blw.ursprungsbezeichnungen-spirituosen-eau_vie_poire',
                                                     'ch.blw.ursprungsbezeichnungen-spirituosen-zuger_kirsch'],
    'ch.ensi.zonenplan-notfallschutz-kernanlagen': [   'ch.ensi.zonenplan-notfallschutz-kernanlagen'],
    'ch.kantone.historische-topografische-namen': [   'ch.kantone.historische-topografische-namen'],
    'ch.pronatura.waldreservate': ['ch.pronatura.waldreservate'],
    'ch.sgpk.maechtigkeit-lockergesteine': [   'ch.sgpk.maechtigkeit-lockergesteine'],
    'ch.swisstopo-vd.geometa-gemeinde': ['ch.swisstopo-vd.geometa-gemeinde'],
    'ch.swisstopo-vd.geometa-grundbuch': ['ch.swisstopo-vd.geometa-grundbuch'],
    'ch.swisstopo-vd.geometa-los': ['ch.swisstopo-vd.geometa-los'],
    'ch.swisstopo-vd.geometa-nfgeom': ['ch.swisstopo-vd.geometa-nfgeom'],
    'ch.swisstopo-vd.geometa-periodische_nachfuehrung': [   'ch.swisstopo-vd.geometa-periodische_nachfuehrung'],
    'ch.swisstopo-vd.geometa-standav': ['ch.swisstopo-vd.geometa-standav'],
    'ch.swisstopo-vd.ortschaftenverzeichnis_plz': [   'ch.swisstopo-vd.ortschaftenverzeichnis_plz'],
    'ch.swisstopo-vd.spannungsarme-gebiete': [   'ch.swisstopo-vd.spannungsarme-gebiete'],
    'ch.swisstopo-vd.stand-oerebkataster': [   'ch.swisstopo-vd.stand-oerebkataster'],
    'ch.swisstopo.dreiecksvermaschung': ['ch.swisstopo.dreiecksvermaschung'],
    'ch.swisstopo.fixpunkte-agnes': ['ch.swisstopo.fixpunkte-agnes'],
    'ch.swisstopo.fixpunkte-hfp1': ['ch.swisstopo.fixpunkte-hfp1'],
    'ch.swisstopo.fixpunkte-hfp2': ['ch.swisstopo.fixpunkte-hfp2'],
    'ch.swisstopo.fixpunkte-lfp1': ['ch.swisstopo.fixpunkte-lfp1'],
    'ch.swisstopo.fixpunkte-lfp2': ['ch.swisstopo.fixpunkte-lfp2'],
    'ch.swisstopo.geoidmodell-ch1903': [   'ch.swisstopo.geoidmodell-ch1903_2',
                                           'ch.swisstopo.geoidmodell-ch1903_3'],
    'ch.swisstopo.geoidmodell-etrs89': [   'ch.swisstopo.geoidmodell-etrs89_2',
                                           'ch.swisstopo.geoidmodell-etrs89_3'],
    'ch.swisstopo.geologie-dosisleistung-terrestrisch': [   'ch.swisstopo.geologie-dosisleistung-terrestrisch'],
    'ch.swisstopo.geologie-eiszeit-lgm': ['ch.swisstopo.geologie-eiszeit-lgm'],
    'ch.swisstopo.geologie-generalkarte-ggk200.metadata': [   'ch.swisstopo.geologie-generalkarte-ggk200.metadata'],
    'ch.swisstopo.geologie-geocover.metadata': [   'ch.swisstopo.geologie-geocover.metadata'],
    'ch.swisstopo.geologie-geodaesie-bouguer_anomalien': [   'ch.swisstopo.geologie-geodaesie-bouguer_anomalien'],
    'ch.swisstopo.geologie-geodaesie-isostatische_anomalien': [   'ch.swisstopo.geologie-geodaesie-isostatische_anomalien'],
    'ch.swisstopo.geologie-geolkarten500.metadata': [   'ch.swisstopo.geologie-geolkarten500.metadata'],
    'ch.swisstopo.geologie-geophysik-aeromagnetische_karte_jura': [   'ch.swisstopo.geologie-geophysik-aeromagnetische_karte_jura'],
    'ch.swisstopo.geologie-geophysik-aeromagnetische_karte_schweiz': [   'ch.swisstopo.geologie-geophysik-aeromagnetische_karte_schweiz'],
    'ch.swisstopo.geologie-geophysik-deklination': [   'ch.swisstopo.geologie-geophysik-deklination'],
    'ch.swisstopo.geologie-geophysik-geothermie': [   'ch.swisstopo.geologie-geophysik-geothermie'],
    'ch.swisstopo.geologie-geophysik-inklination': [   'ch.swisstopo.geologie-geophysik-inklination'],
    'ch.swisstopo.geologie-geophysik-totalintensitaet': [   'ch.swisstopo.geologie-geophysik-totalintensitaet'],
    'ch.swisstopo.geologie-geotechnik-gk500-genese': [   'ch.swisstopo.geologie-geotechnik-gk500-genese'],
    'ch.swisstopo.geologie-geotechnik-gk500-gesteinsklassierung': [   'ch.swisstopo.geologie-geotechnik-gk500-gesteinsklassierung'],
    'ch.swisstopo.geologie-geotechnik-gk500-lithologie_hauptgruppen': [   'ch.swisstopo.geologie-geotechnik-gk500-lithologie_hauptgruppen'],
    'ch.swisstopo.geologie-geotechnik-mineralische_rohstoffe200': [   'ch.swisstopo.geologie-geotechnik-mineralische_rohstoffe200_shape'],
    'ch.swisstopo.geologie-geotechnik-steine_historische_bauwerke': [   'ch.swisstopo.geologie-geotechnik-steine_historische_bauwerke'],
    'ch.swisstopo.geologie-geowege': [   'ch.swisstopo.geologie-geowege_points',
                                         'ch.swisstopo.geologie-geowege_lines'],
    'ch.swisstopo.geologie-gisgeol-flaechen-1000to21000km2': [   'ch.swisstopo.geologie-gisgeol-flaechen-1000to21000km2'],
    'ch.swisstopo.geologie-gisgeol-flaechen-100to1000km2': [   'ch.swisstopo.geologie-gisgeol-flaechen-100to1000km2'],
    'ch.swisstopo.geologie-gisgeol-flaechen-10to100km2': [   'ch.swisstopo.geologie-gisgeol-flaechen-10to100km2'],
    'ch.swisstopo.geologie-gisgeol-flaechen-10x10km': [   'ch.swisstopo.geologie-gisgeol-flaechen-10x10km'],
    'ch.swisstopo.geologie-gisgeol-flaechen-1x1km': [   'ch.swisstopo.geologie-gisgeol-flaechen-1x1km'],
    'ch.swisstopo.geologie-gisgeol-flaechen-gt21000km2': [   'ch.swisstopo.geologie-gisgeol-flaechen-gt21000km2'],
    'ch.swisstopo.geologie-gisgeol-flaechen-lt10km2': [   'ch.swisstopo.geologie-gisgeol-flaechen-lt10km2'],
    'ch.swisstopo.geologie-gisgeol-linien': [   'ch.swisstopo.geologie-gisgeol-linien'],
    'ch.swisstopo.geologie-gisgeol-punkte': [   'ch.swisstopo.geologie-gisgeol-punkte'],
    'ch.swisstopo.geologie-gravimetrischer_atlas.messpunkte': [   'ch.swisstopo.geologie-gravimetrischer_atlas.messpunkte'],
    'ch.swisstopo.geologie-gravimetrischer_atlas.metadata': [   'ch.swisstopo.geologie-gravimetrischer_atlas.metadata_1',
                                                                'ch.swisstopo.geologie-gravimetrischer_atlas.metadata_2'],
    'ch.swisstopo.geologie-spezialkarten_schweiz.metadata': [   'ch.swisstopo.geologie-spezialkarten_schweiz.metadata_poly',
                                                                'ch.swisstopo.geologie-spezialkarten_schweiz.metadata_lines'],
    'ch.swisstopo.images-swissimage.metadata': [   'ch.swisstopo.images-swissimage.metadata-kartenblatt_nummer',
                                                   'ch.swisstopo.images-swissimage.metadata-kartenblatt_name',
                                                   'ch.swisstopo.images-swissimage.metadata-kartenblatt'],
    'ch.swisstopo.landesschwerenetz': [   'ch.swisstopo.landesschwerenetz_all_zl',
                                          'ch.swisstopo.landesschwerenetz_low'],
    'ch.swisstopo.lubis-bildstreifen': ['ch.swisstopo.lubis-bildstreifen'],
    'ch.swisstopo.lubis-luftbilder-dritte-firmen': [   'ch.swisstopo.lubis-luftbilder-dritte-firmen'],
    'ch.swisstopo.lubis-luftbilder-dritte-kantone': [   'ch.swisstopo.lubis-luftbilder-dritte-kantone'],
    'ch.swisstopo.lubis-luftbilder_farbe': [   'ch.swisstopo.lubis-luftbilder_farbe'],
    'ch.swisstopo.lubis-luftbilder_infrarot': [   'ch.swisstopo.lubis-luftbilder_infrarot'],
    'ch.swisstopo.lubis-luftbilder_schraegaufnahmen': [   'ch.swisstopo.lubis-luftbilder_schraegaufnahmen'],
    'ch.swisstopo.lubis-luftbilder_schwarzweiss': [   'ch.swisstopo.lubis-luftbilder_schwarzweiss'],
    'ch.swisstopo.papierkarte-gk300.metadata': [   'ch.swisstopo.papierkarte-gk300.metadata_white_bg'],
    'ch.swisstopo.papierkarte-lhk100.metadata': [   'ch.swisstopo.papierkarte-lhk100.metadata_white_bg',
                                                    'ch.swisstopo.papierkarte-lhk100.metadata_contour',
                                                    'ch.swisstopo.papierkarte-lhk100.metadata_kartenummer',
                                                    'ch.swisstopo.papierkarte-lhk100.metadata_kartename',
                                                    'ch.swisstopo.papierkarte-lhk100.metadata_white_bg_kartename'],
    'ch.swisstopo.papierkarte-lk100-zusammensetzung.metadata': [   'ch.swisstopo.papierkarte-lk100-zusammensetzung.metadata_white_bg',
                                                                   'ch.swisstopo.papierkarte-lk100-zusammensetzung.metadata_contour',
                                                                   'ch.swisstopo.papierkarte-lk100-zusammensetzung.metadata_kartenummer',
                                                                   'ch.swisstopo.papierkarte-lk100-zusammensetzung.metadata_kartename',
                                                                   'ch.swisstopo.papierkarte-lk100-zusammensetzung.metadata_white_bg_kartename'],
    'ch.swisstopo.papierkarte-lk100.metadata': [   'ch.swisstopo.papierkarte-lk100.metadata_white_bg',
                                                   'ch.swisstopo.papierkarte-lk100.metadata_contour',
                                                   'ch.swisstopo.papierkarte-lk100.metadata_kartenummer',
                                                   'ch.swisstopo.papierkarte-lk100.metadata_kartename',
                                                   'ch.swisstopo.papierkarte-lk100.metadata_white_bg_kartename'],
    'ch.swisstopo.papierkarte-lk1000.metadata': [   'ch.swisstopo.papierkarte-lk1000.metadata_white_bg'],
    'ch.swisstopo.papierkarte-lk200.metadata': [   'ch.swisstopo.papierkarte-lk200.metadata_white_bg',
                                                   'ch.swisstopo.papierkarte-lk200.metadata_contour',
                                                   'ch.swisstopo.papierkarte-lk200.metadata_kartenummer',
                                                   'ch.swisstopo.papierkarte-lk200.metadata_kartename',
                                                   'ch.swisstopo.papierkarte-lk200.metadata_white_bg_kartename'],
    'ch.swisstopo.papierkarte-lk25-zusammensetzung.metadata': [   'ch.swisstopo.papierkarte-lk25-zusammensetzung.metadata_white_bg',
                                                                  'ch.swisstopo.papierkarte-lk25-zusammensetzung.metadata_contour',
                                                                  'ch.swisstopo.papierkarte-lk25-zusammensetzung.metadata_kartenummer',
                                                                  'ch.swisstopo.papierkarte-lk25-zusammensetzung.metadata_kartename',
                                                                  'ch.swisstopo.papierkarte-lk25-zusammensetzung.metadata_white_bg_kartename'],
    'ch.swisstopo.papierkarte-lk25.metadata': [   'ch.swisstopo.papierkarte-lk25.metadata_white_bg',
                                                  'ch.swisstopo.papierkarte-lk25.metadata_contour',
                                                  'ch.swisstopo.papierkarte-lk25.metadata_kartenummer',
                                                  'ch.swisstopo.papierkarte-lk25.metadata_kartename',
                                                  'ch.swisstopo.papierkarte-lk25.metadata_white_bg_kartename'],
    'ch.swisstopo.papierkarte-lk50-zusammensetzung.metadata': [   'ch.swisstopo.papierkarte-lk50-zusammensetzung.metadata_white_bg',
                                                                  'ch.swisstopo.papierkarte-lk50-zusammensetzung.metadata_contour',
                                                                  'ch.swisstopo.papierkarte-lk50-zusammensetzung.metadata_kartenummer',
                                                                  'ch.swisstopo.papierkarte-lk50-zusammensetzung.metadata_kartename',
                                                                  'ch.swisstopo.papierkarte-lk50-zusammensetzung.metadata_white_bg_kartename'],
    'ch.swisstopo.papierkarte-lk50.metadata': [   'ch.swisstopo.papierkarte-lk50.metadata_white_bg',
                                                  'ch.swisstopo.papierkarte-lk50.metadata_contour',
                                                  'ch.swisstopo.papierkarte-lk50.metadata_kartenummer',
                                                  'ch.swisstopo.papierkarte-lk50.metadata_kartename',
                                                  'ch.swisstopo.papierkarte-lk50.metadata_white_bg_kartename'],
    'ch.swisstopo.papierkarte-lk500.metadata': [   'ch.swisstopo.papierkarte-lk500.metadata_white_bg'],
    'ch.swisstopo.papierkarte-sfk300.metadata': [   'ch.swisstopo.papierkarte-sfk300.metadata_white_bg'],
    'ch.swisstopo.papierkarte-wk25-zusammensetzung.metadata': [   'ch.swisstopo.papierkarte-wk25-zusammensetzung.metadata_white_bg',
                                                                  'ch.swisstopo.papierkarte-wk25-zusammensetzung.metadata_contour',
                                                                  'ch.swisstopo.papierkarte-wk25-zusammensetzung.metadata_kartenummer',
                                                                  'ch.swisstopo.papierkarte-wk25-zusammensetzung.metadata_kartename',
                                                                  'ch.swisstopo.papierkarte-wk25-zusammensetzung.metadata_white_bg_kartename'],
    'ch.swisstopo.papierkarte-wk50-zusammensetzung.metadata': [   'ch.swisstopo.papierkarte-wk50-zusammensetzung.metadata'],
    'ch.swisstopo.papierkarte-wk50.metadata': [   'ch.swisstopo.papierkarte-wk50.metadata_white_bg',
                                                  'ch.swisstopo.papierkarte-wk50.metadata_contour',
                                                  'ch.swisstopo.papierkarte-wk50.metadata_kartenummer',
                                                  'ch.swisstopo.papierkarte-wk50.metadata_kartename',
                                                  'ch.swisstopo.papierkarte-wk50.metadata_white_bg_kartename'],
    'ch.swisstopo.pixelkarte-pk100.metadata': [   'ch.swisstopo.pixelkarte-pk100.metadata-kartenblatt_nummer',
                                                  'ch.swisstopo.pixelkarte-pk100.metadata-kartenblatt_name',
                                                  'ch.swisstopo.pixelkarte-pk100.metadata-kartenblatt'],
    'ch.swisstopo.pixelkarte-pk1000.metadata': [   'ch.swisstopo.pixelkarte-pk1000.metadata-kartenblatt_nummer',
                                                   'ch.swisstopo.pixelkarte-pk1000.metadata-kartenblatt_name',
                                                   'ch.swisstopo.pixelkarte-pk1000.metadata-kartenblatt'],
    'ch.swisstopo.pixelkarte-pk200.metadata': [   'ch.swisstopo.pixelkarte-pk200.metadata-kartenblatt_nummer',
                                                  'ch.swisstopo.pixelkarte-pk200.metadata-kartenblatt_name',
                                                  'ch.swisstopo.pixelkarte-pk200.metadata-kartenblatt'],
    'ch.swisstopo.pixelkarte-pk25.metadata': [   'ch.swisstopo.pixelkarte-pk25.metadata-kartenblatt_nummer',
                                                 'ch.swisstopo.pixelkarte-pk25.metadata-kartenblatt_name',
                                                 'ch.swisstopo.pixelkarte-pk25.metadata-kartenblatt'],
    'ch.swisstopo.pixelkarte-pk50.metadata': [   'ch.swisstopo.pixelkarte-pk50.metadata-kartenblatt_nummer',
                                                 'ch.swisstopo.pixelkarte-pk50.metadata-kartenblatt_name',
                                                 'ch.swisstopo.pixelkarte-pk50.metadata-kartenblatt'],
    'ch.swisstopo.pixelkarte-pk500.metadata': [   'ch.swisstopo.pixelkarte-pk500.metadata-kartenblatt_nummer',
                                                  'ch.swisstopo.pixelkarte-pk500.metadata-kartenblatt_name',
                                                  'ch.swisstopo.pixelkarte-pk500.metadata-kartenblatt'],
    'ch.swisstopo.skitourenkarte-50.metadata': [   'ch.swisstopo.skitourenkarte-50.metadata'],
    'ch.swisstopo.swissboundaries3d-bezirk-flaeche.fill': [   'ch.swisstopo.swissboundaries3d-bezirk-flaeche.fill'],
    'ch.swisstopo.swissboundaries3d-gemeinde-flaeche.fill': [   'ch.swisstopo.swissboundaries3d-gemeinde-flaeche.fill'],
    'ch.swisstopo.swissboundaries3d-kanton-flaeche.fill': [   'ch.swisstopo.swissboundaries3d-kanton-flaeche.fill'],
    'ch.swisstopo.swissboundaries3d-land-flaeche.fill': [   'ch.swisstopo.swissboundaries3d-land-flaeche.fill'],
    'ch.swisstopo.swissnames3d': [   'ch.swisstopo.swissnames3d_feature_poly',
                                     'ch.swisstopo.swissnames3d_feature_line',
                                     'ch.swisstopo.swissnames3d_feature_point'],
    'ch.swisstopo.transformationsgenauigkeit': [   'ch.swisstopo.transformationsgenauigkeit_2',
                                                   'ch.swisstopo.transformationsgenauigkeit_3'],
    'ch.swisstopo.verschiebungsvektoren-tsp1': [   'ch.swisstopo.verschiebungsvektoren-tsp1'],
    'ch.swisstopo.verschiebungsvektoren-tsp2': [   'ch.swisstopo.verschiebungsvektoren-tsp2'],
    'ch.vbs.armeelogistikcenter': ['ch.vbs.armeelogistikcenter'],
    'ch.vbs.bundestankstellen-bebeco': ['ch.vbs.bundestankstellen-bebeco'],
    'ch.vbs.logistikraeume-armeelogistikcenter': [   'ch.vbs.logistikraeume-armeelogistikcenter'],
    'ch.vbs.patrouilledesglaciers-a_rennen': [   'ch.vbs.patrouilledesglaciers-a_rennen'],
    'ch.vbs.patrouilledesglaciers-z_rennen': [   'ch.vbs.patrouilledesglaciers-z_rennen'],
    'ch.vbs.retablierungsstellen': ['ch.vbs.retablierungsstellen'],
    'ch.vbs.sachplan-infrastruktur-militaer_anhoerung': [   'ch.vbs.sachplan-infrastruktur-militaer_anhoerung_polygons_raster',
                                                            'ch.vbs.sachplan-infrastruktur-militaer_anhoerung_polygons',
                                                            'ch.vbs.sachplan-infrastruktur-militaer_anhoerung_points',
                                                            'ch.vbs.sachplan-infrastruktur-militaer_anhoerung_points',
                                                            'ch.vbs.sachplan-infrastruktur-militaer_anhoerung_lines'],
    'ch.vbs.sachplan-infrastruktur-militaer_kraft': [   'ch.vbs.sachplan-infrastruktur-militaer_kraft_polygons_raster',
                                                        'ch.vbs.sachplan-infrastruktur-militaer_kraft_polygons',
                                                        'ch.vbs.sachplan-infrastruktur-militaer_kraft_points',
                                                        'ch.vbs.sachplan-infrastruktur-militaer_kraft_points',
                                                        'ch.vbs.sachplan-infrastruktur-militaer_kraft_lines'],
    'org.epsg.grid_2056': [   'org.epsg.grid_2056_1',
                              'org.epsg.grid_2056_2',
                              'org.epsg.grid_2056_3',
                              'org.epsg.grid_2056_4',
                              'org.epsg.grid_2056_5',
                              'org.epsg.grid_2056_6',
                              'org.epsg.grid_2056_7',
                              'org.epsg.grid_2056_8',
                              'org.epsg.grid_2056_9',
                              'org.epsg.grid_2056_10',
                              'org.epsg.grid_2056_11',
                              'org.epsg.grid_2056_12',
                              'org.epsg.grid_2056_13'],
    'org.epsg.grid_21781': [   'org.epsg.grid_21781_1',
                               'org.epsg.grid_21781_2',
                               'org.epsg.grid_21781_3',
                               'org.epsg.grid_21781_4',
                               'org.epsg.grid_21781_5',
                               'org.epsg.grid_21781_6',
                               'org.epsg.grid_21781_7',
                               'org.epsg.grid_21781_8',
                               'org.epsg.grid_21781_9',
                               'org.epsg.grid_21781_10',
                               'org.epsg.grid_21781_11',
                               'org.epsg.grid_21781_12',
                               'org.epsg.grid_21781_13'],
    'org.epsg.grid_4326': [   'org.epsg.grid_4326_1',
                              'org.epsg.grid_4326_2',
                              'org.epsg.grid_4326_3',
                              'org.epsg.grid_4326_4',
                              'org.epsg.grid_4326_5',
                              'org.epsg.grid_4326_6',
                              'org.epsg.grid_4326_7',
                              'org.epsg.grid_4326_8',
                              'org.epsg.grid_4326_9',
                              'org.epsg.grid_4326_10',
                              'org.epsg.grid_4326_11',
                              'org.epsg.grid_4326_12',
                              'org.epsg.grid_4326_13']}